### ISSUE TITLE
Problema ao utilizar a função de unir Databases de Whatsapp

### ISSUE THREAD

**Issue by RuanAlmeidaTSI** [AvillaDaniel/AvillaForensics#12]
Bom dia
Estou tendo um pequeno problema ao utilizar a ferramenta merge_databases.exe.

Há uma grande possiblidade de que o erro seja meu, pois posso estar utilizando a ferramenta de modo errado, sem contar que estou tentando utilizá-la para unir databases geradas a partir do Whatsapp Business, e não do Whatsapp normal.
Por isso, estou fazendo este post para pedir que por favor me auxilie com essas dúvidas.

Ao tentar iniciá-lo utilizando o comando mostrado na página principal do github (C:\Forensics-3-6\bin\merge\merge_databases_exe>merge_databases.exe -lv) o seguinte erro aparece:

Analisando arquivos .db na pasta: C:\Forensics-3-6\bin\merge\merge_databases_exe
Banco de dados de referência com o conteúdo atual deve manter o nome padrão msgstore.db
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
  File "merge_databases.py", line 207, in \<module\>
  File "merge_databases.py", line 204, in main
  File "merge_databases.py", line 187, in batch_merge
  File "merge_databases.py", line 177, in read_files
NameError: name 'exit' is not defined

Desde ja agradeço.
Aguardo ansiosamente sua reposta.

**Comment by AvillaDaniel** [comment]
Esse módulo será descontinuado, deixarei essa tafera a cargo do IPED que faz isso com excelência. Obrigado.
